<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

    <div class="card m-3">
        <div class="card-header">
            <h4 class="card-title">Objetivo de la plataforma</h4>
        </div>
        <div class="card-body">
            <p>El objetivo de la plataforma es brindar un servicio de gestión de eventos y contactos orientado a
                maximizar la productividad, conseguir clientes y aumentar la base de contactos.</p>
        </div>
    </div>

    <div class="card m-3">
        <div class="card-header">
            <h4 class="card-title">Entidades / Secciones</h4>
        </div>
        <div class="card-body">
            <b>Eventos</b>
            <p>Esta es la entidad principal, desde la misma se crean y configuran los eventos de la plataforma.</p>

            <b>Contactos</b>
            <p>Aquí se encuentran todos los contactos registrados en la plataforma. Los mismos se van incrementando por
                cada evento donde confirmen personas. Esta base se puede utilizar para envío de promociones como por
                ejemplo propuestas de evento de cumpleaños.
            </p>
            <b>Invitados</b>
            <p>Aquí se encuentran todos los invitados registrados por los propietarios de los eventos.
            </p>
            <b>Consultas</b>
            <p>Aquí se encuentran todas las consultas recibidas en los eventos.
            </p>
            <b>Correo destino de consulta</b>
            <p>Aquí se pueden configurar cuentas de emails para recibir una notificación cada vez que alguien hace una
                consulta por un evento.
            </p>
            <b>Lugares</b>
            <p>Aquí se configuran los lugares donde se realizarán los eventos.
            </p>
            <b>Flyer</b>
            <p>Aquí se cargan las imagenes que se utilizaran como imagen principal en la landing del evento.
            </p>
            <b>Fotos</b>
            <p> Aquí se cargan las fotos asociadas a los lugares previamente definidos.
            </p>
            <b>DetalleEvento</b>
            <p>Aquí se cargan descripciones de evento que luego se utilizan al momento de crear un evento.
            </p>
        </div>
    </div>

    <div class="card m-3">
        <div class="card-header">
            <h4 class="card-title">Gestión de evento</h4>
        </div>
        <div class="card-body">
            <p>En primera instancia, configurar lugares, flyer, fotos y detalles de evento. Si se omite alguna configuración, se puede agregar o modificar en cualquier momento, incluso luego de haber creado un evento.</p>

            <p>Para configurar un evento, ingresar al menu "Eventos" y hacer click en "+". Se debe
                completar los siguientes datos:</p>


            <p> <b>Nombre</b>: Define el nombre del evento y link del mismo.</p>

            <p> <b>Clave</b>: Campo opcional. Permite agregar un nivel de seguridad en la confirmación del evento. En general
                se sugiere no configurar una clave.
            </p>

            <p><b>Lugar</b>: Define el lugar del evento. Deben definirse previamente los lugares disponibles.
            </p>

            <p> <b>Flyer</b>: Define la foto principal en la landing del evento.</p>
            <p> <b>DetalleEvento</b>: Permite cargar una descripción del evento. Deben definirse previamente las descripciones
                disponibles.</p>
            <p><b>Fecha</b>: Define la fecha del evento</p>
            <p><b>Hora y Minutos</b>: Define la hora y minutos en el que comienza el evento.</p>

            <p>Luego de crear el evento, al acceder al listado de eventos, en la columna final, se encuentra el link único para este evento. Comparta dicho link con los interesados.</p>
        </div>
    </div>


</div>