<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

        <div id="appcountdown">

            <countdown deadline="<?php echo $evento->getFecha()->format("F d, Y "); ?><?php echo $evento->getHora(); ?>:<?php echo $evento->getMinutos(); ?>"></countdown>

        </div>

</div>


<?php
$this->headScript()
    ->appendFile('/shared/vuejs/vue.js', 'text/javascript')
    ->appendFile('/main/vue/countdown/countdown.js', 'text/javascript')
    ->appendFile('/main/vue/countdown/appcountdown.js', 'text/javascript');

?>




<style>
    .vuejs-countdown {
        padding: 0;
        margin: 0;
    }
    .vuejs-countdown li {
        display: inline-block;
        margin: 0 8px;
        text-align: center;
        position: relative;
    }
    .vuejs-countdown li p {
        margin: 0;
    }
    .vuejs-countdown li:after {
        /*content: ":";*/
        position: absolute;
        top: 0;
        right: -13px;
        font-size: 32px;
    }
    .vuejs-countdown li:first-of-type {
        margin-left: 0;
    }
    .vuejs-countdown li:last-of-type {
        margin-right: 0;
    }
    .vuejs-countdown li:last-of-type:after {
        content: "";
    }
    .vuejs-countdown .digit {
        font-size: 32px;
        font-weight: 600;
        line-height: 1.4;
        margin-bottom: 0;
    }
    .vuejs-countdown .text {
        text-transform: uppercase;
        margin-bottom: 0;
        font-size: 10px;
    }
</style>

