<?php foreach ($evento->getLugar()->getFotos() as $foto): ?>

    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 col-3 p-0" >
        <img src="<?php echo $foto->getImagen_fp(); ?>" class="rounded img-fluid" data-toggle="modal"
             data-target="#foto-<?php echo $foto->getId(); ?>" />

    </div>

<?php endforeach; ?>

<?php foreach ($evento->getLugar()->getFotos() as $foto): ?>

    <div class="modal" tabindex="-100" role="dialog"
         id="foto-<?php echo $foto->getId(); ?>"
         aria-labelledby="foto-<?php echo $foto->getId(); ?>" data-keyword="true" data-backdrop="false">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Foto <b><?php echo $evento->getLugar(); ?></b></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <img src="<?php echo $foto->getImagen_fp(); ?>" class="rounded img-fluid">
                </div>
            </div>
        </div>
    </div>

<?php endforeach; ?>
