<?php if ($evento && $evento->getLugar()): ?>
    <h4 class="title"><?php echo $evento->getLugar(); ?></h4>

    <h5> Dirección: <?php echo $evento->getLugar()->getDireccion(); ?></h5>
    <?php if ($evento->getLugar()->getFotos()): ?>

        <div class="row">
            <?php foreach ($evento->getLugar()->getFotos() as $foto): ?>
                <div class="col-md-6 col-xs-12 pb-3">
                    <img src="<?php echo $foto->getImagen_fp(); ?>" class="rounded img-fluid" data-toggle="modal"
                         data-target="#foto-<?php echo $foto->getId(); ?>">

                </div>

                <div class="modal" tabindex="-100" role="dialog"
                     id="foto-<?php echo $foto->getId(); ?>"
                     aria-labelledby="foto-<?php echo $foto->getId(); ?>" data-keyword="true" data-backdrop="false"
                     >
                    <div class="modal-dialog modal-lg" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Foto <b><?php echo $evento->getLugar(); ?></b></h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <img src="<?php echo $foto->getImagen_fp(); ?>" class="rounded img-fluid">
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>

    <?php endif; ?>

<?php endif; ?>
