<?php if ($evento && $evento->getFlyer()): ?>
    <div class="page-header header-filter" data-parallax="true"
         style="background-image: url( <?php echo $evento->getFlyer()->getImagen_fp(); ?> ); transform: translate3d(0px, 0px, 0px);">
    </div>
<?php else: ?>
    <div class="page-header header-filter" data-parallax="true"
         style="background-image: url(/img/city.jpg); transform: translate3d(0px, 0px, 0px);">
    </div>
<?php endif; ?>


<div class="main main-raised">
    <div class="profile-content">
        <div class="container">
            <div class="row">
                <div class="col-md-6 ml-auto mr-auto">

                    <div class="profile">
                        <?php echo $this->partial("landing/main/partial/avatar", ["evento" => $evento]); ?>


                        <div class="name">
                            <?php if ($evento && $evento->getContacto()): ?>
                                <h3 class="title"><?php echo $evento->getContacto()->getNombreCompleto(); ?></h3>

                            <?php else: ?>
                                <h3 class="title">Propietario sin confirmar</h3>
                            <?php endif; ?>


                            <?php if ($evento && $evento->getFecha()): ?>
                                <h5>Fecha del evento: <?php echo $evento->getFecha()->format("d-m-Y"); ?></h5>
                            <?php else: ?>
                                <h6>Fecha: A confirmar!</h6>
                            <?php endif; ?>

                            <?php echo $this->partial("landing/main/partial/form", ["evento" => $evento]); ?>



                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6 col-xs-12">
                    <?php echo $this->partial("landing/main/partial/lugar", ["evento" => $evento]); ?>
                    <?php echo $this->partial("landing/main/partial/detalle", ["evento" => $evento]); ?>

                </div>

                <div class="col-md-6 col-xs-12">
                    <?php echo $this->partial("landing/main/partial/confirmados", ["evento" => $evento]); ?>

                </div>

            </div>

            <br><br><br><br><br>

        </div>
    </div>
</div>