

<button class="btn btn-social btn-fill" data-toggle="modal"
        data-target="#minvitados"><i class="material-icons">edit</i> Editar</button>


<div class="modal" tabindex="-100" role="dialog" id="minvitados"
     aria-labelledby="minvitados" data-keyword="true" data-backdrop="false">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Gestion de <b>Invitados</b></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <?php if ($this->evento && $this->evento->getEstado() === \Eventos\Entity\Evento::OWNER): ?>
                        <p>Gestiona tu lista de invitados. Te asistiremos en perdirles que confirmen el evento enviando las
                            instrucciones a los datos de contacto.</p>
                    <?php endif; ?>
                    <?php if ($this->evento): ?>
                        <div id="app">

                            <tableguest :pevento="<?php echo $evento->getId(); ?>" :pentities='<?php echo $evento->getInvitadosJson(); ?>'
                                        :powner='<?php echo $evento->isOwner(); ?>'></tableguest>

                        </div>
                    <?php endif; ?>

                </div>

            </div>
        </div>
    </div>
</div>



<?php
$this->headScript()
    ->appendFile('/shared/vuejs/vue.js', 'text/javascript')
    ->appendFile('/main/vue/invitados/rowGuest.js', 'text/javascript')
    ->appendFile('/main/vue/invitados/tableGuest.js', 'text/javascript')
    ->appendFile('/main/vue/invitados/formGuest.js', 'text/javascript')
    ->appendFile('/main/vue/invitados/app.js', 'text/javascript');

?>

