<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <h4 class="title">Invitados</h4>

    <table class="table">
        <?php if ($evento && count($evento->getInvitados())): ?>
            <?php foreach ($evento->getInvitados() as $invitado): ?>
                <tr>
                    <td><?php echo $invitado->getNombre(); ?></td>
                </tr>

            <?php endforeach; ?>

        <?php else: ?>
            Lista Vacia.
        <?php endif; ?>


    </table>

    <div id="app">
        <addguest :pnombre="''" :pcelular="''" :pevento="<?php echo $evento->getId(); ?>"></addguest>
    </div>
</div>





<?php
$this->headScript()
    ->appendFile('/shared/vuejs/vue.js', 'text/javascript')
    ->appendFile('/main/vue/invitados/addguest.js', 'text/javascript')
    ->appendFile('/main/vue/invitados/app.js', 'text/javascript');
?>

