
    <a href="/eventos/ayuda/main" class="card-link text-success">
        <div class="card mt-3">
            <div class="card-body">
                <p class="text-center"><i class="material-icons" style="font-size: 4rem">help</i></p>
                <h5 class="card-title text-center"> Ayuda </h5>
                <p class="text-center">Guía de la plataforma</p>
            </div>
        </div>
    </a>
