<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <h5>Gestión</h5>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
        <a href="/eventos/evento/grid" class="card-link text-primary">
            <div class="card mb-3">
                <div class="card-body">
                    <p class="text-center"><i class="material-icons" style="font-size: 4rem">date_range</i></p>
                    <h5 class="card-title text-center"> Eventos</h5>
                </div>
            </div>
        </a>
    </div>

    <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
        <a href="/eventos/contacto/grid" class="card-link text-primary">
            <div class="card mb-3">
                <div class="card-body">
                    <p class="text-center"><i class="material-icons" style="font-size: 4rem">account_box</i></p>
                    <h5 class="card-title text-center"> Contactos</h5>
                </div>
            </div>
        </a>
    </div>

    <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
        <a href="/eventos/consulta/grid" class="card-link text-primary">
            <div class="card mb-3">
                <div class="card-body">
                    <p class="text-center"><i class="material-icons" style="font-size: 4rem">send</i></p>
                    <h5 class="card-title text-center"> Consultas</h5>
                </div>
            </div>
        </a>
    </div>

    <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
        <a href="/eventos/invitado/grid" class="card-link text-primary">
            <div class="card mb-3">
                <div class="card-body">
                    <p class="text-center"><i class="material-icons" style="font-size: 4rem">face</i></p>
                    <h5 class="card-title text-center"> Invitados </h5>
                </div>
            </div>
        </a>
    </div>
</div>
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <h5>Configuración</h5>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
        <a href="/eventos/lugar/grid" class="card-link text-warning">
            <div class="card mb-3">
                <div class="card-body">
                    <p class="text-center"><i class="material-icons" style="font-size: 4rem">place</i></p>
                    <h5 class="card-title text-center"> Lugar</h5>
                </div>
            </div>
        </a>
    </div>

    <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
        <a href="/eventos/flyer/grid" class="card-link text-warning">
            <div class="card mb-3">
                <div class="card-body">
                    <p class="text-center"><i class="material-icons" style="font-size: 4rem">insert_photo</i></p>
                    <h5 class="card-title text-center"> Flyer</h5>
                </div>
            </div>
        </a>
    </div>

    <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
        <a href="/eventos/fotos/grid" class="card-link text-warning">
            <div class="card mb-3">
                <div class="card-body">
                    <p class="text-center"><i class="material-icons" style="font-size: 4rem">photo_library</i></p>
                    <h5 class="card-title text-center"> Fotos</h5>
                </div>
            </div>
        </a>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
        <a href="/eventos/detalle-evento/grid" class="card-link text-warning">
            <div class="card mb-3">
                <div class="card-body">
                    <p class="text-center"><i class="material-icons" style="font-size: 4rem">list</i></p>
                    <h5 class="card-title text-center"> Detalle</h5>
                </div>
            </div>
        </a>
    </div>
</div>