<?php
echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
    ->appendStylesheet('/shared/material-desing/bootstrap-material-design.min.css')
    ->appendStylesheet('/shared/material-icons/material-icons.css')
    ->appendStylesheet('/template/material-kit/css/mkp.css')
    ->appendStylesheet('/shared/font-awesome/css/font-awesome.min.css');

echo $this->headStyle();
?>


<!-- Material Design for Bootstrap fonts and icons -->
<!--<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons">-->

<!-- Material Design for Bootstrap CSS -->
<!--<link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">-->

