<?php echo $this->doctype(); ?>

<html lang="UTF-8">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <?php echo $this->headTitle($this->translate('BUDA BS AS'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->partial('landing/layout/css'); ?>


    </head>

    <body class="profile-page ">
<?php echo $this->content; ?>
<?php echo $this->partial('landing/layout/js'); ?>
    </body>
</html>
